server:
  port: 8081

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: 3600000 # 1 hour

spring:
  application:
    name: AUTH-SERVICE

  # MySql
  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/authdb
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
  #JPA
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  # OAuth2 & Security
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${REDIRECT_URI}
            scope:
              - email
              - profile

# Service Discovery (Eureka)
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

# Monitoring
management:
  endpoints:
    web:
      exposure:
        include: "*"   # expose all endpoints
  endpoint:
    health:
      show-details: always

  boot:
    admin:
      client:
        url: ${ADMIN_URL:http://localhost:9090}
        instance:
          prefer-ip: true