server:
  port: ${PORT:8080}

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: 3600000

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:

        # ================= AUTH SERVICE =================
        - id: auth-service
          uri: ${AUTH_SERVICE_URL}
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        # ================= QUANTITY SERVICE =================
        - id: quantity-service
          uri: ${QUANTITY_SERVICE_URL}
          predicates:
            - Path=/api/v1/quantities/**
          filters:
            - StripPrefix=2
            - AuthenticationFilter

  boot:
    admin:
      client:
        url: ${ADMIN_SERVER_URL}

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

# OPTIONAL (can keep or remove)
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}